### ISSUE TITLE
key type?

### ISSUE THREAD

**Issue by jcdc404** [jedisct1/rust-sealed_box#1]
What kind of key is required for this to work properly/safely? I see that it takes a [u8;32], but what should be used to generate this?
x25519, ed25519, curve25519, or?

**Comment by jcdc404** [comment]
After digging through the libsodium gitbook I see that it's an X25519 key. Will the keypair generated from the ed25519_compact/x25519 module be safe to use with this package?

**Comment by jedisct1** [comment]
This crate has a [`KeyPair::create()`](https://docs.rs/sealed_box/latest/sealed_box/struct.KeyPair.html#method.create) function that creates a key pair.

So, just use that :)

**Comment by jedisct1** [comment]
The [README](https://github.com/jedisct1/rust-sealed_box#sealed-boxes-for-rustwebassembly) file also includes a usage example, that generates a new key pair.
